USE [master]
GO

/****** Object:  Database [LabDatabase]    Script Date: 2018/07/12 14:22:24 ******/
CREATE DATABASE [LabDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LabDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\LabDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LabDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\LabDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LabDatabase] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LabDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LabDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LabDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LabDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LabDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LabDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [LabDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LabDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LabDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LabDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LabDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LabDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LabDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LabDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LabDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LabDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LabDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LabDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LabDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LabDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LabDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LabDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LabDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LabDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LabDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [LabDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LabDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LabDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LabDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LabDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LabDatabase] SET QUERY_STORE = OFF
GO

USE [LabDatabase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [LabDatabase] SET  READ_WRITE 
GO


